### ISSUE TITLE
::execute should try to call #execute if no block passed

### ISSUE THREAD

**Issue by JelF** [JelF/xquery#4]
There are possible another ways to hold it, e.g. accept a symbol (or proc) instead of block

**Comment by fiscal-cliff** [comment]
Could you separate the actual execution of combined query from the process of its building. Sometimes it would be very useful to just get the relation as is for further modifications. Sometimes the query should be invoked immediately. So I do hope that you will add following features. I see this as returning the actual scope after all. So there is no need to call anything at the end of query building process.

**Comment by JelF** [comment]
They are separated. 
You can call Class.new(params).<%= any method you define to execute it %> and get the execution result. But i can add instance versions of `with` and `execute` if you want to. And probably remove class method `execute` (but not `with`)
